### ISSUE TITLE
Unmapped iconCode

### ISSUE THREAD

**Issue by GSzabados** [jaydeethree/Home-Assistant-weatherdotcom#45] opened 2024-12-19 07:36 UTC
Hi,

This morning the following error popped up:

```
This error originated from a custom integration.

Logger: custom_components.weatherdotcom.coordinator
Source: custom_components/weatherdotcom/coordinator.py:248
integration: Weather.com (documentation, issues)
First occurred: 08:29:08 (1 occurrences)
Last logged: 08:29:08

Unmapped iconCode from TWC Api. (44 is Not Available (N/A)) "None".
```

Following a timeout.

```
2024-12-19 08:28:33.368 ERROR (MainThread) [custom_components.weatherdotcom.coordinator] Error getting current weather, will retry. Exception: <class 'TimeoutError'>. Details: 
2024-12-19 08:28:48.945 ERROR (MainThread) [custom_components.weatherdotcom.coordinator] Error getting current weather. Exception: <class 'TimeoutError'>. Details: 
2024-12-19 08:28:58.946 ERROR (MainThread) [custom_components.weatherdotcom.coordinator] Error getting daily weather, will retry. Exception: <class 'TimeoutError'>. Details: 
2024-12-19 08:29:08.713 WARNING (MainThread) [custom_components.weatherdotcom.coordinator] Unmapped iconCode from TWC Api. (44 is Not Available (N/A)) "None". 
```

**Comment by jaydeethree** [comment] 2024-12-19 17:40
This looks to me like a temporary network issue - is this still happening?

**Comment by GSzabados** [comment] 2024-12-19 18:09
Yes, that looks like a network issue, but I am not sure what was this unmapped iconCode...

Just happened this morning, for a 20 minutes period a few times with those TimeoutError

**Comment by jaydeethree** [comment] 2024-12-19 18:30
>Yes, that looks like a network issue, but I am not sure what was this unmapped iconCode...

That can be ignored - it's caused by the network timeout. I made a small code change in https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/391937256e1c558283be4f3a11c4d8cb0990b14a to handle this situation better. I'm not planning to make a new release just for this change, but it will be included in the next release.

**Closed by jaydeethree** 2024-12-19 18:30 UTC

**Comment by GSzabados** [comment] 2024-12-19 19:29
Cheers! No worries!
