### ISSUE TITLE
Air quaility entity + local alerts

### ISSUE THREAD

**Issue by jakcyl** [jaydeethree/Home-Assistant-weatherdotcom#38] opened 2024-08-25 14:38 UTC
would it possibile to add an entity for air quality indexes  and/or local alerts?

**Comment by jaydeethree** [comment] 2024-08-25 15:33
Duplicate of https://github.com/jaydeethree/Home-Assistant-weatherdotcom/issues/21 - air quality data and local alerts are not available in the API used by this integration.

**Closed by jaydeethree** 2024-08-25 15:33 UTC
